import { EnumGender } from './genders';
import { lang, proficiency } from './languages';

export interface IFirebaseProfile {
  birthday?: string;
  workRadius?: string;
  youtube?: string;
  whatsapp?: string;
  country?: string;
  gender?: EnumGender;
  city?: string;
  university?: string;
  postalCode?: string;
  coverPictureUrl?: string;
  created?: boolean;
  linkedin?: string;
  instagram?: string;
  type: 'fisica' | 'moral';
  twitter?: string;
  imdb?: string;
  reviews?: string;
  tiktok?: string;
  altEmail?: string;
  nickname?: string;
  state?: string;
  headline?: string;
  email: string;
  profilePictureUrl?: string;
  subareas?: string[];
  characteristics?: string;
  website?: string;
  address?: string;
  languages?: { lang: lang; proficiency: proficiency }[];
  remoteWork?: boolean;
  facebook?: string;
  googleMapsLink?: string;
  certifications?: string;
  lastname?: string;
  asociations?: string;
  profilePicture?: string;
  vimeo?: string;
  altEmail2?: string;
  phone?: string;
  awards?: string;
  probono?: boolean;
  searchName: string[];
  name?: string;
  altPhone?: string;
  location?: string;
  altPhone2?: string;
  reviewCount?: number;
}

export interface IFirebaseProfileUpdate {
  birthday?: string;
  workRadius?: string;
  youtube?: string;
  whatsapp?: string;
  country?: string;
  gender?: EnumGender;
  city?: string;
  university?: string;
  postalCode?: string;
  coverPictureUrl?: string;
  linkedin?: string;
  instagram?: string;
  type?: 'fisica' | 'moral';
  created?: boolean;
  twitter?: string;
  imdb?: string;
  reviews?: string;
  tiktok?: string;
  altEmail?: string;
  nickname?: string;
  state?: string;
  headline?: string;
  email?: string;
  profilePictureUrl?: string;
  subareas?: string[];
  characteristics?: string;
  website?: string;
  address?: string;
  languages?: { lang: lang; proficiency: proficiency }[];
  remoteWork?: boolean;
  facebook?: string;
  googleMapsLink?: string;
  certifications?: string;
  lastname?: string;
  asociations?: string;
  vimeo?: string;
  altEmail2?: string;
  phone?: string;
  awards?: string;
  probono?: boolean;
  name?: string;
  altPhone?: string;
  location?: string;
  altPhone2?: string;
  reviewCount?: number;
}
